DELETE FROM account;
INSERT INTO account(id, name, created_at, updated_at) VALUES (1, 'user1', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (2, 'user2', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (3, 'user3', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (4, 'user4', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (5, 'user5', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (6, 'user6', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (7, 'user7', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (8, 'user8', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (9, 'user9', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO account(id, name, created_at, updated_at) VALUES (10, 'user10', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
