spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:h2:mem:/kotlin_maven_demo;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  output:
    ansi:
      enabled: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true
