spring:
  output:
    ansi:
      enabled: always
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_mybatis_kotlin_db1
    username: sa
    password:
#  jackson:
#    serialization:
#      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
