spring:
  datasource:
    sql-script-encoding: UTF-8
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/tmp/h2_mybatis_kotlin_db1
    username: sa
    password:
  output:
    ansi:
      enabled: always
mybatis:
  configuration:
    map-underscore-to-camel-case: true
